export const athenaViolations: string[] = [
  "VIOL_FILETYPE",
  "VIOL_METHOD",
  "VIOL_MANDATORY_HEADER",
  "VIOL_HTTP_RESPONSE_STATUS",
  "VIOL_REQUEST_MAX_LENGTH",
  "VIOL_FILE_UPLOAD",
  "VIOL_FILE_UPLOAD_IN_BODY",
  "VIOL_XML_MALFORMED",
  "VIOL_JSON_MALFORMED",
  "VIOL_ASM_COOKIE_MODIFIED",
  "VIOL_HTTP_PROTOCOL_MULTIPLE_HOST_HEADERS",
  "VIOL_HTTP_PROTOCOL_BAD_HOST_HEADER_VALUE",
  "VIOL_HTTP_PROTOCOL_UNPARSABLE_REQUEST_CONTENT",
  "VIOL_HTTP_PROTOCOL_NULL_IN_REQUEST",
  "VIOL_HTTP_PROTOCOL_BAD_HTTP_VERSION",
  "VIOL_HTTP_PROTOCOL_CRLF_CHARACTERS_BEFORE_REQUEST_START",
  "VIOL_HTTP_PROTOCOL_NO_HOST_HEADER_IN_HTTP_1_1_REQUEST",
  "VIOL_HTTP_PROTOCOL_BAD_MULTIPART_PARAMETERS_PARSING",
  "VIOL_HTTP_PROTOCOL_SEVERAL_CONTENT_LENGTH_HEADERS",
  "VIOL_HTTP_PROTOCOL_CONTENT_LENGTH_SHOULD_BE_A_POSITIVE_NUMBER",
  "VIOL_EVASION_DIRECTORY_TRAVERSALS",
];

export const supportedEvasions: { [key: string]: string } = {
  "Directory traversals": "VIOL_EVASION_DIRECTORY_TRAVERSALS",
};

export const supportedHttpProtocols: { [key: string]: string } = {
  "Multiple host headers": "VIOL_HTTP_PROTOCOL_MULTIPLE_HOST_HEADERS",
  "Header name with no header value":
    "VIOL_HTTP_PROTOCOL_BAD_HOST_HEADER_VALUE",
  "Null in request": "VIOL_HTTP_PROTOCOL_NULL_IN_REQUEST",
  "Retrieving data. Wait a few seconds and try to cut or copy again.":
    "VIOL_HTTP_PROTOCOL_BAD_MULTIPART_PARAMETERS_PARSING",
};
